apiVersion: v1
kind: Service
metadata:
  name: vyenfita-ai
  namespace: vyenfita
  labels:
    app: vyenfita-ai
spec:
  type: ClusterIP
  selector:
    app: vyenfita-ai
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
  sessionAffinity: None
