/**
 * VYENFITA Business Intelligence Service
 * 
 * Orchestrates the full BI flow:
 * 1. User asks question in natural language
 * 2. AI generates SQL
 * 3. SQL is validated for safety
 * 4. Query is executed
 * 5. Chart is auto-recommended
 * 6. Anomalies are detected
 * 7. Results are returned
 * 
 * @version 1.0.0
 */

import { prisma } from '../database/client';
import { SecretService } from '../security/secret.service';
import { auditService } from '../audit/audit.service';
import { logger } from '../observability/logger';
import { SchemaDiscoveryService } from './schema-discovery.service';
import { QueryExecutorService } from './query-executor.service';
import { NLToSQLService } from './nl-to-sql.service';
import { ChartRecommender } from './chart-recommender.service';
import { AnomalyDetector, AnomalyResult } from './anomaly-detector.service';
import {
  DataSourceConfig,
  TableSchema,
  QueryResult,
} from './data-source.interface';

export interface AskQuestionInput {
  tenantId: string;
  userId: string;
  dataSourceId: string;
  question: string;
  context?: Record<string, any>;
  detectAnomalies?: boolean;
}

export interface AskQuestionResult {
  question: string;
  sql: string;
  explanation: string;
  confidence: number;
  tablesUsed: string[];
  followUpQuestions: string[];
  caveats: string[];
  data: QueryResult;
  chart: {
    type: string;
    config: Record<string, any>;
    reasoning: string;
  };
  anomalies?: AnomalyResult;
  meta: {
    durationMs: number;
    tokensUsed: number;
    costUsd: number;
  };
}

export class BIService {
  private secretService: SecretService;

  constructor() {
    this.secretService = new SecretService();
  }

  /**
   * Answer a natural language question
   */
  async ask(input: AskQuestionInput): Promise<AskQuestionResult> {
    const startTime = Date.now();

    // ============================================================
    // STEP 1: Load data source
    // ============================================================
    const dataSource = await prisma.secret.findFirst({
      where: {
        id: input.dataSourceId,
        tenantId: input.tenantId,
        deletedAt: null,
      },
    });

    if (!dataSource) {
      throw new Error('Data source not found');
    }

    const config = this.mapToDataSourceConfig(dataSource);

    // ============================================================
    // STEP 2: Discover schema
    // ============================================================
    let schemas: TableSchema[];
    try {
      schemas = await SchemaDiscoveryService.discover(config, this.secretService);
    } catch (error) {
      logger.error('Schema discovery failed', {
        dataSourceId: input.dataSourceId,
        error: error instanceof Error ? error.message : 'Unknown',
      });
      throw new Error(
        `Cannot access data source schema: ${error instanceof Error ? error.message : 'Unknown error'}`
      );
    }

    // ============================================================
    // STEP 3: Generate SQL from question
    // ============================================================
    const sqlGeneration = await NLToSQLService.generate({
      tenantId: input.tenantId,
      userId: input.userId,
      question: input.question,
      schemas,
      dialect: config.type === 'mysql' ? 'mysql' : 'postgresql',
      context: input.context,
    });

    if (!sqlGeneration.safetyPassed) {
      await auditService.log({
        tenantId: input.tenantId,
        userId: input.userId,
        eventType: 'security',
        action: 'bi.query_blocked',
        resource: 'data_source',
        resourceId: input.dataSourceId,
        details: {
          question: input.question,
          sql: sqlGeneration.sql,
          reasons: sqlGeneration.safetyReasons,
        },
        status: 'failure',
      });

      throw new Error(
        `Query generated by AI is unsafe: ${sqlGeneration.safetyReasons?.join('; ')}`
      );
    }

    // ============================================================
    // STEP 4: Execute query
    // ============================================================
    const data = await QueryExecutorService.execute(
      config,
      sqlGeneration.sql,
      this.secretService
    );

    // ============================================================
    // STEP 5: Recommend chart
    // ============================================================
    const chart = ChartRecommender.recommend(data);

    // ============================================================
    // STEP 6: Detect anomalies (optional)
    // ============================================================
    let anomalies: AnomalyResult | undefined;
    if (input.detectAnomalies !== false && data.rows.length > 10) {
      anomalies = this.detectAnomaliesInResult(data);
    }

    // ============================================================
    // STEP 7: Audit
    // ============================================================
    const durationMs = Date.now() - startTime;

    await auditService.log({
      tenantId: input.tenantId,
      userId: input.userId,
      eventType: 'access',
      action: 'bi.query_success',
      resource: 'data_source',
      resourceId: input.dataSourceId,
      details: {
        question: input.question,
        sql: sqlGeneration.sql,
        rowCount: data.rowCount,
        confidence: sqlGeneration.confidence,
      },
      status: 'success',
      duration: durationMs,
    });

    return {
      question: input.question,
      sql: sqlGeneration.sql,
      explanation: sqlGeneration.explanation,
      confidence: sqlGeneration.confidence,
      tablesUsed: sqlGeneration.tablesUsed,
      followUpQuestions: sqlGeneration.followUpQuestions,
      caveats: sqlGeneration.caveats,
      data,
      chart,
      anomalies,
      meta: {
        durationMs,
        tokensUsed: sqlGeneration.tokensUsed,
        costUsd: sqlGeneration.costUsd,
      },
    };
  }

  // ============================================================
  // PRIVATE
  // ============================================================

  private mapToDataSourceConfig(record: any): DataSourceConfig {
    const metadata = record.metadata as any;

    return {
      id: record.id,
      tenantId: record.tenantId,
      name: record.name,
      type: metadata.type || 'postgresql',
      host: metadata.host,
      port: metadata.port,
      database: metadata.database,
      username: metadata.username,
      passwordEncrypted: record.vaultPath || metadata.passwordEncrypted,
      sslEnabled: metadata.sslEnabled !== false,
      connectionTimeoutMs: metadata.connectionTimeoutMs || 10000,
      createdAt: record.createdAt,
      updatedAt: record.updatedAt,
    };
  }

  private detectAnomaliesInResult(data: QueryResult): AnomalyResult | undefined {
    // Find first numeric column
    for (const col of data.columns) {
      const values = data.rows.map((r) => r[col]);
      const allNumbers = values.every(
        (v) => v === null || typeof v === 'number' || !isNaN(Number(v))
      );

      if (allNumbers && values.length >= 10) {
        const numericValues = values
          .filter((v) => v !== null)
          .map((v) => Number(v));

        if (numericValues.length >= 10) {
          return AnomalyDetector.detect(numericValues, { method: 'zscore' });
        }
      }
    }

    return undefined;
  }
}

let instance: BIService | undefined;

export function getBIService(): BIService {
  if (!instance) {
    instance = new BIService();
  }
  return instance;
        }
